FROM amazoncorretto:8-alpine

LABEL       author="AshlynOrSomethin" maintainer="ashlyn@onlyhit.xyz"
LABEL       org.opencontainers.image.source="https://github.com/AshlynOrSomethin/pelican-images"
LABEL       org.opencontainers.image.licenses="MIT"

RUN         apk add --no-cache curl ffmpeg iproute2 git sqlite python3 tzdata ca-certificates bind-tools fontconfig freetype libstdc++ lsof jq build-base musl-locales musl-locales-lang netcat-openbsd bash \
            && adduser -D -h /home/container container

ENV         LC_ALL=en_US.UTF-8
ENV         LANG=en_US.UTF-8
ENV         LANGUAGE=en_US.UTF-8

USER        container
ENV         USER=container HOME=/home/container
WORKDIR     /home/container

COPY        ./entrypoint.sh /entrypoint.sh
CMD         [ "/bin/bash", "/entrypoint.sh" ]